### ISSUE TITLE
Bootstrap classes not being copied to fixed header

### ISSUE THREAD

**Issue by AlanGRutter** [alalonde/angular-scrollable-table#24]
If I have a class e.g. bg-primary on the original THEAD element, this is not propagated onto the div with classes th-inner and box. The foreground colour is inherited from the THEAD (as white) but the background colour does not get inherited and stays white also - hence the headers are invisible.

**Comment by alalonde** [comment]
Please submit a plunkr or jsfiddle demonstrating the issue.

**Comment by alalonde** [comment]
Closed due to inactivity.
