### ISSUE TITLE
table scrolls when you're interacting with header on Chrome and IE

### ISSUE THREAD

**Issue by kwieckowski-neducatio** [alalonde/angular-scrollable-table#27]
Tested on: Chrome 40 / IE 11

1. Open demo fiddle
2. Scroll to the bottom of the table
3. Click and hold your mouse button on any header and move your mouse (i.e. try to highlight header's title)

Weird... I know ;) The problem doesn't exist on Firefox though..

**Comment by alalonde** [comment]
Whoa, that is weird.

**Comment by alalonde** [comment]
Can't reproduce with Chrome 50.  Procrastination FTW!
