### ISSUE TITLE
Could you add the Ability to set the Height for the Container with Attribute

### ISSUE THREAD

**Issue by squadwuschel** [alalonde/angular-scrollable-table#32]
Hi,

is it possibble to provide the containerheight with an Attribute like:

      template: '<div class="scrollableContainer" ng-style="{\'height\': containerHeight }">' +
                    '<div class="headerSpacer"></div>' +
                    '<div class="scrollArea" ng-transclude></div>' +
                  '</div>'

and Usage:

       <div scrollable-table watch="ctrl.resultModel.Entries" container-height='"600px"'>

Or perhaps to get the Height from the sourrounded Container height?

that would be nice and is there a Version avaible which has no sort implementation just the fixed header implementation?

thx SquadWuschel

(VERY Great Directive!!)

**Comment by alalonde** [comment]
Hello, 

You can set the height via CSS as a percent or fixed amount.  Also, if you don't want the sort functionality, simply omit the `sortable-header` attribute from each `th` element.
