### ISSUE TITLE
Fixed first column of table

### ISSUE THREAD

**Issue by neesonqk** [alalonde/angular-scrollable-table#33]
Fixed first column of table

**Comment by alalonde** [comment]
?  More detail, please

**Comment by randymelder** [comment]
I'm having an issue when I reload the table data, the column headers do not render correctly. It appears that the first <th> width never readjusts. 
![screen shot 2015-06-25 at 12 05 03 pm](https://cloud.githubusercontent.com/assets/857124/8363261/9fcdd86c-1b32-11e5-8cef-05df932d5001.png)
![screen shot 2015-06-25 at 12 04 23 pm](https://cloud.githubusercontent.com/assets/857124/8363260/9fcd32fe-1b32-11e5-911c-c23a8d244d8f.png)
