### ISSUE TITLE
Headers Truncated

### ISSUE THREAD

**Issue by LukeMauldin** [alalonde/angular-scrollable-table#35]
See the screenshot below.  There is just one <tr> but some of the column titles should wrap around to a new line and the size of the header should grow.  However, as you can see the size of the header is always fixed.  I have tried putting in '<br />' to force line breaks and I have tried increasing the height of the header as shown in the css below but that did not work either.

```
.scrollableContainer {
  height: 550px;

  .headerSpacer {
    height: 60px;
  }
}

.scrollArea table .th-inner {
  height: 60px;
  line-height: 60px;
}
```

![screen shot 2015-07-07 at 7 00 47 am](https://cloud.githubusercontent.com/assets/1440808/8545625/04774b4e-2476-11e5-935e-75ee89faed9e.png)

**Comment by alalonde** [comment]
This is by design.  You can a `title` attribute which on hover will display the full column header.
