### ISSUE TITLE
prevent issues with "-webkit-overflow-scrolling: touch" in .scrollArea

### ISSUE THREAD

**Issue by edamon** [alalonde/angular-scrollable-table#36]
I would suggest adding "-webkit-overflow-scrolling: auto;" to the .scrollArea css class until a solution is found to enable inertial scrolling and still have the headers show up.  this would have saved me a couple hours.  I would also make that clearer in the readme.rm.  thank you for this excellent module!

**Comment by alalonde** [comment]
Thanks for the feedback -- but did you not see the comment in the `.scrollArea` css?  I explicitly have `-webkit-overflow-scrolling: touch` in there but commented out.

**Comment by edamon** [comment]
Yes, I did see that, and if it wasn't for that comment, i would have spent
MUCH more time troubleshooting, so thank you!  The issue I had is that in
the site I'm working on, there was already a -webkit-overflow-scrolling:
touch at a high level in the DOM, so even though you had it commented out,
it still took me some time to figure out that "-webkit-overflow-scrolling:
touch" was this issue.  by explicitly setting that to "auto" on the
.scrollArea class, it prevents "external" code from breaking this excellent
module.  By doing so, I'm able to have "-webkit-overflow-scrolling: touch"
as the default behavior, and can override that to "auto" on .scrollArea.
