### ISSUE TITLE
minor issue in using custom comparatorFn

### ISSUE THREAD

**Issue by ReynardLe** [alalonde/angular-scrollable-table#53]
Hi,

In the sort portion of sortableHeader, you have:

scope.toggleSort = function (e) {
            if (scope.isActive()) {
              tableController.toggleSort();
            } else {
              tableController.setSortExpr(expr);
            }
            tableController.doSort(scope[attrs.comparatorFn]);
            e.preventDefault();
          };
...

I can't use attrs.comparatorFn as html automatically renders my comparatorFn to comparatorfn (case-insensitive). Changing the code to use attrs.comparatorfn solves this issue. (Tried to send a PR but didn't have access, so I report this instead.)

Thanks,
Reynard.

**Comment by alalonde** [comment]
Directive attributes should be defined using kebab-case. See https://github.com/alalonde/angular-scrollable-table/blob/master/demo/index.html#L44
