### ISSUE TITLE
Make sorting stable

### ISSUE THREAD

**Issue by piotr-dobrogost** [alalonde/angular-scrollable-table#60]
As `Array.prototype.sort` is [not](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) guaranteed to be stable I think the library should guarantee stabilty itself using technique described in this [anwser](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) on *Array.sort Sorting Stability in Different Browsers* question on Stackoverflow.

**Comment by alalonde** [comment]
We could add an additional configuration input that is just a sorting function, with API e.g.
```
// returns a number 
function(itemA, itemB) {
  return itemA.localeCompare(itemB);
}
```

**Comment by alalonde** [comment]
If you want to put together a PR implementing this I would be happy to merge it in.

**Comment by piotr-dobrogost** [comment]
> We could add an additional configuration input that is just a sorting function, with API e.g.

Sorry, but I don't get the idea.

**Comment by alalonde** [comment]
We support per-column sort comparator functions, so you should be able to just pass in your own implementation. See https://github.com/alalonde/angular-scrollable-table/blob/master/demo/index.html#L44
