### ISSUE TITLE
TypeError: $element.find(...).scroll is not a function

### ISSUE THREAD

**Issue by Pumych** [alalonde/angular-scrollable-table#61]
Any ideas?

**Comment by erikkallen** [comment]
same here

**Comment by HARIPRASADHARI** [comment]
Add JQuery before the Angular js files

**Comment by werdoJC** [comment]
Hi @HARIPRASADHARI  Have tried adding JQuery on my side, but still has the same error.
This is my code in my _Layout.cshtml
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/angular-scrollable-table/angular-scrollable-table.js"></script>

**Comment by werdoJC** [comment]
Thanks @HARIPRASADHARI  . It worked for me.
